apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-ki
#  namespace: exp
spec:
  schedule: '@every 15s'
  type: PodChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
      - app
      labelSelectors:
        chaos: blast-here
    duration: '1000s'
