apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
  namespace: chaos-exp
spec:
  action: pod-failure
  mode: one
  duration: '60s'
  selector:
    namespaces:
    - app
    labelSelectors:      
        chaos: blast-here
