kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: account-cluster-viewer-ofqol

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-cluster-viewer-ofqol
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - chaos-mesh.org
  resources: [ "*" ]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-cluster-viewer-ofqol
subjects:
- kind: ServiceAccount
  name: account-cluster-viewer-ofqol
  namespace: default
roleRef:
  kind: ClusterRole
  name: role-cluster-viewer-ofqol
  apiGroup: rbac.authorization.k8s.io

