apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adapt-prod-app
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: prod
  source:
    path: prod/adapt-prod-child-app
    repoURL: git@bitbucket.org:adapt-bfctech/argo-applications.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
