apiVersion: apps/v1
kind: StatefulSet
metadata:
        name: prom-server
        labels:
                app: prometheus
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: prometheus
        serviceName: "prometheus"
        template:
                metadata:
                        labels:
                                app: prometheus
                spec:
                        containers:
                        - name: prom-con
                          image: ubuntu/prometheus
                          volumeMounts: 
                          - name: prom-persistent-storage
                            mountPath: /Users/devx/bfc/monitoring/repo/kube
                        volumes:
                        - name: prom-persistent-storage
                          persistentVolumeClaim:
                                  claimName: pvc-hostpath
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30008
