apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/test"
