apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adapt-qa-cart
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: qa
    server: 'https://kubernetes.default.svc'
  source:
    path: cart/charts/qa/cart
    repoURL: 'git@bitbucket.org:adapt-bfctech/adapt-infra.git'
    targetRevision: qa
  project: qa
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
